### ISSUE TITLE
Choose splitting dimensions

### ISSUE THREAD

**Issue by qverron** [elgw/nd2tool#1]
Hi
It would be practical to be able to choose which dimensions nd2tool splits images upon, for instance specifying "positions" but not "channels" to get individual multi-plane, multi-channel images in a memory-efficient way.
Thanks!
Q

**Comment by elgw** [comment]
In version 0.1.3 I've added the command line option **--composite** which will create a composite image per field of view, i.e. will not split over color. 

It remains to select color maps automatically or to have some clever default options. As it is no color maps are set, in that case ImageJ automagically display the channels with different colors. Let me know if this is what you wanted and how we can make it more useful.

**Comment by elgw** [comment]
Closing this for now. Please submit a new issue for the option to choose colors.
